name: Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - actions

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build and publish the code
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install npm Packages
        run: cd client && npm install

      - name: Run Build Script
        run: cd client && npm run build && mv build release

      - name: Set environment for github-release
        run: |
          echo ::set-env name=RELEASE_TAG::"v1.0.0"
          echo ::set-env name=RELEASE_NAME::"v1.0.0"

      - name: Publish
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: ./client/release
