name: Themer Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.6" # The Go version to download (if necessary) and use.
      - run: go build

      - name: Publish
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          files: themer
          allow_override: true
